[package]
name = "slice-utils"
version = "1.0.0"
edition = "2021"

license = "MIT"
description = "A collection of slice utils, like itertools."
authors = ["Kyllingene"]
repository = "https://github.com/Kyllingene/slice-utils"

[features]
default = []
std = []
